- name: Deploy Draftly App
  hosts: app_servers
  become: yes
  vars:
    app_dir: /home/ubuntu/draftly
  tasks:

    - name: Pull latest backend and frontend images
      shell: |
        docker compose pull
      args:
        chdir: "{{ app_dir }}"
      environment:
        IMAGE_TAG: "{{ IMAGE_TAG }}"

    - name: Deploy containers
      shell: |
        docker compose up -d --force-recreate --no-build
      args:
        chdir: "{{ app_dir }}"
      environment:
        IMAGE_TAG: "{{ IMAGE_TAG }}"

    - name: Clean up dangling images
      shell: docker image prune -f
